---
version: "3.7"

name: kaltura_player_content_security_police
services:
  gateway:
    image: nginx:stable-alpine
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "2324:443"
    volumes:
      - ./container/conf:/etc/nginx
      - ./container/certs:/etc/nginx/certs
      - ./src:/usr/share/nginx/html
